services:
  reverse-proxy:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - c-http-server-1
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: 30M
    networks:
      - c-http-net

  c-http-server: &http-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - c-http-net
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: 30M
    expose:
      - "8000"

  c-http-server-1:
    <<: *http-server
    container_name: c-http-server-1

networks:
  c-http-net:
    driver: bridge
