services:
  c-http-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: 30M
    expose:
      - "8000"
    ports:
      - "8000:8000"
